[package]
name = "gsk-memory-leak"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
gdk-pixbuf = "0.15.11"
gtk4 = "0.4.8"

[features]
default = []
leak = []
